In [79]:
import numpy as np

Array Operations

In [80]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [81]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [82]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [83]:
a1-a2

array([-5, -5, -5, -5, -5])

In [84]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [85]:
a1%a2

array([1, 2, 3, 4, 5])

In [86]:
a1//a2

array([0, 0, 0, 0, 0])

In [87]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [88]:
#Broadcasting
l= [10,20,30,40]
arr = np.array(l)

In [89]:
arr + 10

array([20, 30, 40, 50])

In [90]:
#vector operations
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [91]:
arr2=arr2+10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and shallow copy

In [92]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [93]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [94]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [95]:
a[4:6] *10

array([50, 60])

In [96]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [97]:
b = a.copy()

In [98]:
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [99]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [103]:
#matrix operations
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

array([[5, 6],
       [7, 8]])

In [104]:
A

array([[1, 2],
       [3, 4]])

In [105]:
B

array([[5, 6],
       [7, 8]])

In [107]:
A@B #METHOD1: MULTIPLICATION OF MATRIX

array([[19, 22],
       [43, 50]])

In [110]:
np.dot(A,B) #METHOD2: MULTIPLICATION OF MATRIX

array([[19, 22],
       [43, 50]])

In [111]:
#TRANSPOSE
A.T

array([[1, 3],
       [2, 4]])

In [112]:
B.T

array([[5, 7],
       [6, 8]])

Advanced Array Manipulation

In [113]:
#stacking array
    #YOU CANNOT USE MATRIX 
    #YOU SHOULD USE VECTORS

In [117]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [118]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [119]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [120]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [121]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [124]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [125]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [128]:
split=np.vsplit(c,4)

In [129]:
for i in split:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
