In [1]:
import numpy as np

Basic Array Creation

In [6]:
arr = np.array([1,2,3,4]) #array
arr

array([1, 2, 3, 4])

In [8]:
a = [1,2,3.5,4,"hello"] #list
a 

[1, 2, 3.5, 4, 'hello']

In [11]:
np.array(a) #everything will be converted to unicode i.e strings

array(['1', '2', '3.5', '4', 'hello'], dtype='<U32')

In [12]:
a2 = [1,2,3.5]
np.array(a2) #everything will be converted to float

array([1. , 2. , 3.5])

In [13]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function

In [30]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [31]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

Random Generation Function

In [35]:
 np.random.rand(10)

array([0.7965251 , 0.57196039, 0.85875133, 0.56427791, 0.44009681,
       0.88811792, 0.65566938, 0.4308378 , 0.19295206, 0.16445747])

In [38]:
np.random.randn(10)

array([ 4.22400186,  0.09842889,  1.98959906, -1.55381757,  0.95698155,
        0.11472423,  0.13630974,  2.1640062 ,  1.26115874, -0.10881548])

In [41]:
np.random.randint(10,20,10)

array([19, 16, 18, 11, 12, 17, 12, 16, 17, 12], dtype=int32)

In [43]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr.shape

(3, 3)

In [45]:
arr.size

9

In [46]:
arr.dtype

dtype('int64')

 Array Methods

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr.min()

np.int64(1)

In [50]:
arr.max()

np.int64(9)

In [51]:
arr.sum()

np.int64(45)

In [53]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [54]:
arr.mean()

np.float64(5.0)

In [55]:
arr.std()

np.float64(2.581988897471611)

In [56]:
arr.argmax()

np.int64(8)

In [57]:
arr.argmin()

np.int64(0)

Reshaping and resizing

In [58]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [60]:
arr = arr.reshape(6,5)