In [1]:
import numpy as np

Numpy Indexing And Slicing Of Vectors

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
arr[9]

np.int64(20)

In [13]:
arr[1:5]

array([12, 13, 14, 15])

In [14]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
arr[:5]

array([11, 12, 13, 14, 15])

In [16]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [20]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [21]:
arr[4]

np.int64(15)

Numpy Indexing And Slicing Of Matrix

In [22]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [23]:
arr[0]

array([1, 2, 3, 4, 5])

In [24]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [25]:
arr[5]

array([26, 27, 28, 29, 30])

In [31]:
arr[0,0]

np.int64(1)

In [33]:
arr[0,4]

np.int64(5)

In [34]:
arr[5,4]

np.int64(30)

In [36]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [38]:
slice_2 = arr[3: ,3: ]
slice_2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [40]:
slice_3 = arr[:,2]
slice_3

array([ 3,  8, 13, 18, 23, 28])

Boolean Indexing

In [41]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [44]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])